/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sendmsg;


import com.amazonaws.services.sqs.AmazonSQS;
import com.amazonaws.services.sqs.AmazonSQSClientBuilder;
import com.amazonaws.services.sqs.model.SendMessageRequest;

public class App {
//    public String geGreeting()
//    {
//        return "Hello world.";
//    }

    public static void main(String[] args){
        final AmazonSQS sqs = AmazonSQSClientBuilder.defaultClient();

        String queue = "";
        switch (args[0]){
            case "a":
                queue +="url/messageQueueA";
                break;
            case "b":
                queue +="url/messageQueueB";
                break;
            case "c":
                queue +="url/messageQueueC";
                break;
        }


        SendMessageRequest send_msg_request = new SendMessageRequest()
                .withQueueUrl(queue)
                .withMessageBody("hello world")
                .withDelaySeconds(5);
        sqs.sendMessage(send_msg_request);
        //System.out.println(new App().geGreeting());
    }
}
