/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AWS.SQS.Message.Queues;

import com.amazonaws.services.sqs.AmazonSQS;
import com.amazonaws.services.sqs.AmazonSQSClientBuilder;
import com.amazonaws.services.sqs.model.SendMessageRequest;

public class App {
//    public String geGreeting()
//    {
//        return "Hello world.";
//    }

    public static void main(String[] args){
        final AmazonSQS sqs = AmazonSQSClientBuilder.defaultClient();


        SendMessageRequest send_msg_request = new SendMessageRequest()
                .withQueueUrl("https://sqs.us-west-2.amazonaws.com/424220637898/messageQueue")
                .withMessageBody("hello world")
                .withDelaySeconds(5);
        sqs.sendMessage(send_msg_request);
        //System.out.println(new App().geGreeting());
    }
}
