/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package receivemsg;

import com.amazonaws.services.sqs.AmazonSQS;
import com.amazonaws.services.sqs.AmazonSQSClientBuilder;
import com.amazonaws.services.sqs.model.Message;

import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        final AmazonSQS sqs = AmazonSQSClientBuilder.defaultClient();
        String queue = "";
        switch (args[0]){
            case "a":
                queue +="url/messageQueueA";
                break;
            case "b":
                queue +="url/messageQueueB";
                break;
            case "c":
                queue +="url/messageQueueC";
                break;
        }

        List<Message> messages = sqs.receiveMessage(queue).getMessages();
        System.out.println(messages.toString());
        //System.out.println(new App().getGreeting());
    }
}
