/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package receivemsg;

import com.amazonaws.services.sqs.AmazonSQS;
import com.amazonaws.services.sqs.AmazonSQSClientBuilder;
import com.amazonaws.services.sqs.model.Message;

import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        final AmazonSQS sqs = AmazonSQSClientBuilder.defaultClient();

        List<Message> messages = sqs.receiveMessage("https://sqs.us-west-2.amazonaws.com/424220637898/messageQueue").getMessages();
        System.out.println(messages.toString());
        //System.out.println(new App().getGreeting());
    }
}
